### ISSUE TITLE
Cannot run on windows

### ISSUE THREAD

**Issue by Yakumounr** [endlessm/xdelta3-dir-patcher#22]
"The code was written with portability in mind so its in Python3 and contained in one script (even though it makes developments a bit trick"

line 37. from grp import getgrgid

grp - "This module provides access to the Unix group database. It is available on all Unix versions."  it doesn't exist on windows.

It's a shame, the only other equivalent xdelta3 tools with recursive support I can find are java, and I don't want to have to install java :D

**Comment by sgnn7** [comment]
@Yakumounr Hmm, you make a good point though "portability" in this case meant more "*nix-based systems". If I get time, I can try to maybe see how difficult the implementation here would be but since grp and pwd modules are tiny, the patch would probably be small too if you want to give it a try.

**Comment by sgnn7** [comment]
@Yakumounr Got this at least in runnable state for Windows but I didn't spend time porting the tests.

You need:
- Python3 installed
- `xdelta3.exe` in the directory or on the path (https://github.com/jmacd/xdelta-gpl/releases)
- GIDs/UIDs aren't handled (shouldn't be a problem)
- When doing `apply` you must use `--ignore-euid` option

Closing the issue as resolved but I do expect bugs - however, given how much of a pain it is to develop this feature, if you find problems that are not trivial, you might be on your own.

**Comment by Yakumounr** [comment]
Thank you! I've not tried it yet but I'm sure this will be useful in the future for myself and others.
