### ISSUE TITLE
Can this script react efficiently to the case where the source name is unknown?

### ISSUE THREAD

**Issue by i30817** [endlessm/xdelta3-dir-patcher#25]
I mean, imagine if you as a patch distributor want to patch a set of files, if the user has them. But the user is a idiot and renames his files, so you can't make the filename the patch applies to, part of the patch file filename.

you naturally do something like this:

```
for source in [list of user dirs or zips]:
    for patch in [list of patches]:
        if xdelta3-dir-patcher apply source patch output_dir:
            break
    else:
       log_error(...)
```

The problem here is that `xdelta3-dir-patcher apply source patch output_dir` is doing a lot of work to 'harmonize' the source into tar-file in memory (if i'm reading correctly) in order to be able to apply it to the external application xdelta.

This is fine, but i'd prefer a option for the (much more efficient in this case):

```
for source in [list of user dirs or zips]:
    preprocessed_source = xdelta3-dir-patcher.pre_process(source)
    for patch in [list of patches]:
        if xdelta3-dir-patcher apply-pre preprocessed_source  patch output_dir:
            break
    else:
       log_error(...)
```
ie: the 'tar file creation' would have been n times at the most, instead of n*x at the most. This is a recurring problem for any app that wants to make applying patches to a set of files 'idiot proof', Xdelta prevents accidental errors by having a checksum of the source already, so this is the obvious way to do it.

**Comment by i30817** [comment]
Not sure if this is even a good idea after thinking about it a bit actually. The usecase i was thinking of is adequately covered by the target filename being part of the patch filename, and a user that renames the source and then tries to apply a patch is asking for trouble...

**Comment by sgnn7** [comment]
@i30817 Yeah, this just wouldn't be efficient either way - if a file is renamed then you have to go through all of the files in the directory and try to figure out if there is a file with a matching hash to a stray xdelta with a missing `source`. I think it's doable but the level of effort you would need to code something up for this extreme edge case where the user themselves mucked around the code is completely not worth the trouble vs doing a check before patch install and making sure that the FS tree is in the expected state and reinstalling missing things if that's the case.

PS: Sadly, this code is also now in maintenance mode so if any new features are needed, it would probably have to come from external contributors as I don't have much spare time to maintain the source anymore.

I'll close this issue for now but feel free to reopen if you strongly feel that this is a needed feature.
